server:
  port: 10086
spring:
  application:
    name: shop-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  server:
    eviction-interval-timer-in-ms: 5000